import { forwardRef } from 'react';

interface PrintableInvoiceProps {
  challan: any;
}

export const PrintableInvoice = forwardRef<HTMLDivElement, PrintableInvoiceProps>(({ challan }, ref) => {
  if (!challan) return null;

  // Auto-generate a dummy E-Way bill number based on Challan ID for demonstration
  const ewayBillNumber = `EWB-${challan.id.replace(/-/g, '').substring(0, 12).toUpperCase()}`;
  
  // Calculate Grand Total
  const grandTotal = challan.items?.reduce((sum: number, item: any) => sum + (item.unitPrice * item.quantity), 0) || 0;
  
  // Fake GST Calculation (18% for example, just for UI display)
  const taxableValue = grandTotal / 1.18;
  const cgst = (grandTotal - taxableValue) / 2;
  const sgst = cgst;

  return (
    <div 
      ref={ref} 
      style={{ 
        padding: '40px', 
        fontFamily: 'Arial, sans-serif', 
        backgroundColor: 'white',
        color: '#333',
        width: '100%',
        boxSizing: 'border-box'
      }}
    >
      {/* HEADER */}
      <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '2px solid #343a40', paddingBottom: '20px', marginBottom: '20px' }}>
        <div>
          <h1 style={{ fontSize: '2rem', margin: '0 0 5px 0', color: '#17a2b8', textTransform: 'uppercase', letterSpacing: '1px' }}>FUNDSROOM ERP</h1>
          <div style={{ fontSize: '0.9rem', color: '#555' }}>
            123 Enterprise Avenue, Tech Park<br />
            Mumbai, Maharashtra 400001<br />
            GSTIN: 27AADCB2230M1Z2<br />
            support@fundsroom.com
          </div>
        </div>
        <div style={{ textAlign: 'right' }}>
          <h2 style={{ fontSize: '1.8rem', margin: '0 0 10px 0', color: '#343a40', textTransform: 'uppercase' }}>Tax Invoice</h2>
          <table style={{ fontSize: '0.9rem', marginLeft: 'auto', textAlign: 'left' }}>
            <tbody>
              <tr><td style={{ paddingRight: '10px', color: '#777', fontWeight: 'bold' }}>Invoice No:</td><td>{challan.challanNumber}</td></tr>
              <tr><td style={{ paddingRight: '10px', color: '#777', fontWeight: 'bold' }}>Date:</td><td>{new Date(challan.createdAt).toLocaleDateString()}</td></tr>
              <tr><td style={{ paddingRight: '10px', color: '#777', fontWeight: 'bold' }}>Generated By:</td><td>{challan.user?.name || 'System'}</td></tr>
              <tr><td style={{ paddingRight: '10px', color: '#777', fontWeight: 'bold' }}>E-Way Bill:</td><td><strong>{ewayBillNumber}</strong></td></tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* BILL TO */}
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '30px', backgroundColor: '#f8fafc', padding: '15px', borderRadius: '4px', border: '1px solid #eef2f9' }}>
        <div>
          <h3 style={{ margin: '0 0 10px 0', fontSize: '1rem', color: '#7b859a', textTransform: 'uppercase' }}>Billed To:</h3>
          <div style={{ fontWeight: 'bold', fontSize: '1.1rem', marginBottom: '5px' }}>{challan.customer?.name}</div>
          <div style={{ fontSize: '0.9rem', color: '#555' }}>
            {challan.customer?.businessName && <>{challan.customer.businessName}<br/></>}
            {challan.customer?.address && <>{challan.customer.address}<br/></>}
            Mobile: {challan.customer?.mobile}<br />
            GSTIN: {challan.customer?.gstNumber || 'Unregistered'}
          </div>
        </div>
      </div>

      {/* ITEMS TABLE */}
      <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: '30px' }}>
        <thead>
          <tr style={{ backgroundColor: '#343a40', color: 'white', textAlign: 'left' }}>
            <th style={{ padding: '12px', border: '1px solid #343a40' }}>#</th>
            <th style={{ padding: '12px', border: '1px solid #343a40' }}>Item Description (SKU)</th>
            <th style={{ padding: '12px', border: '1px solid #343a40', textAlign: 'right' }}>Qty</th>
            <th style={{ padding: '12px', border: '1px solid #343a40', textAlign: 'right' }}>Rate (₹)</th>
            <th style={{ padding: '12px', border: '1px solid #343a40', textAlign: 'right' }}>Amount (₹)</th>
          </tr>
        </thead>
        <tbody>
          {challan.items?.map((item: any, i: number) => (
            <tr key={i}>
              <td style={{ padding: '12px', border: '1px solid #d2d6de' }}>{i + 1}</td>
              <td style={{ padding: '12px', border: '1px solid #d2d6de' }}>
                <div style={{ fontWeight: 'bold' }}>{item.productName}</div>
                <div style={{ fontSize: '0.8rem', color: '#777' }}>SKU: {item.productSku} | Cat: {item.productCategory}</div>
              </td>
              <td style={{ padding: '12px', border: '1px solid #d2d6de', textAlign: 'right' }}>{item.quantity}</td>
              <td style={{ padding: '12px', border: '1px solid #d2d6de', textAlign: 'right' }}>{item.unitPrice.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
              <td style={{ padding: '12px', border: '1px solid #d2d6de', textAlign: 'right' }}>{(item.quantity * item.unitPrice).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* TOTALS & TAXES */}
      <div style={{ display: 'flex', justifyContent: 'space-between' }}>
        <div style={{ flex: 1, paddingRight: '40px' }}>
          <h4 style={{ margin: '0 0 5px 0' }}>Terms & Conditions:</h4>
          <ul style={{ margin: 0, paddingLeft: '20px', fontSize: '0.8rem', color: '#555' }}>
            <li>Goods once sold will not be taken back.</li>
            <li>Interest @ 18% p.a. will be charged if payment is delayed.</li>
            <li>Subject to Mumbai jurisdiction.</li>
          </ul>
        </div>
        <div style={{ flex: '0 0 300px' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.95rem' }}>
            <tbody>
              <tr>
                <td style={{ padding: '8px', borderBottom: '1px solid #eee', fontWeight: 'bold', color: '#555' }}>Taxable Value:</td>
                <td style={{ padding: '8px', borderBottom: '1px solid #eee', textAlign: 'right' }}>₹{taxableValue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
              </tr>
              <tr>
                <td style={{ padding: '8px', borderBottom: '1px solid #eee', fontWeight: 'bold', color: '#555' }}>CGST (9%):</td>
                <td style={{ padding: '8px', borderBottom: '1px solid #eee', textAlign: 'right' }}>₹{cgst.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
              </tr>
              <tr>
                <td style={{ padding: '8px', borderBottom: '1px solid #eee', fontWeight: 'bold', color: '#555' }}>SGST (9%):</td>
                <td style={{ padding: '8px', borderBottom: '1px solid #eee', textAlign: 'right' }}>₹{sgst.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
              </tr>
              <tr style={{ backgroundColor: '#f8fafc' }}>
                <td style={{ padding: '12px 8px', fontWeight: 'bold', fontSize: '1.2rem' }}>Grand Total:</td>
                <td style={{ padding: '12px 8px', textAlign: 'right', fontWeight: 'bold', fontSize: '1.2rem', color: '#1e8e3e' }}>
                  ₹{grandTotal.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      
      {/* SIGNATURE BLOCK */}
      <div style={{ marginTop: '50px', textAlign: 'right' }}>
        <div style={{ borderTop: '1px solid #333', width: '200px', display: 'inline-block', paddingTop: '5px', textAlign: 'center', fontSize: '0.9rem', fontWeight: 'bold' }}>
          Authorized Signatory
        </div>
      </div>

    </div>
  );
});

PrintableInvoice.displayName = 'PrintableInvoice';
